"""
Handle the exception thrown by the code below by using try and except blocks.

for i in ['a', 'b', 'c']:
	print(i**2))
"""

#######################
## SOLUTION BY KEVIN ##
#######################

try:
	for i in ['a', 'b', 'c']:
		print(i**2)
except:
	print('An error occured!')